# Source of truth: docs/03-DATA-MODEL.md. Mirrored in config/taxonomy.yaml;
# if they drift, the taxonomy file wins and tests must fail loudly.
from enum import Enum


class RootCause(str, Enum):
    BALANCE_SHORTFALL = "BALANCE_SHORTFALL"
    ISSUER_DEGRADED = "ISSUER_DEGRADED"
    MANDATE_DEFECT = "MANDATE_DEFECT"
    INSTRUMENT_DEFECT = "INSTRUMENT_DEFECT"
    TECHNICAL_TRANSIENT = "TECHNICAL_TRANSIENT"
    RISK_BLOCK = "RISK_BLOCK"
    UNKNOWN = "UNKNOWN"


class CauseSubtype(str, Enum):
    # MANDATE_DEFECT
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
    AMOUNT_EXCEEDS_CAP = "AMOUNT_EXCEEDS_CAP"
    FREQUENCY_VIOLATION = "FREQUENCY_VIOLATION"
    NOT_YET_ACTIVE = "NOT_YET_ACTIVE"
    # INSTRUMENT_DEFECT
    CARD_EXPIRED = "CARD_EXPIRED"
    ACCOUNT_CLOSED = "ACCOUNT_CLOSED"
    ACCOUNT_FROZEN = "ACCOUNT_FROZEN"
    ACCOUNT_DORMANT = "ACCOUNT_DORMANT"
    # ISSUER_DEGRADED
    ISSUER_DOWN = "ISSUER_DOWN"
    RAIL_DEGRADED = "RAIL_DEGRADED"
    # other
    NONE = "NONE"


class Disposition(str, Enum):
    RECOVERABLE_TIMING = "RECOVERABLE_TIMING"
    RECOVERABLE_IMMEDIATE = "RECOVERABLE_IMMEDIATE"
    RECOVERABLE_ACTION = "RECOVERABLE_ACTION"
    TERMINAL = "TERMINAL"


class ActionType(str, Enum):
    SCHEDULE_PRESENTMENT = "SCHEDULE_PRESENTMENT"
    PRESENT_NOW = "PRESENT_NOW"
    PRE_DEBIT_NOTICE = "PRE_DEBIT_NOTICE"
    TOPUP_NUDGE = "TOPUP_NUDGE"
    SEND_PAYMENT_LINK = "SEND_PAYMENT_LINK"
    REQUEST_REAUTH = "REQUEST_REAUTH"
    REQUEST_INSTRUMENT_UPDATE = "REQUEST_INSTRUMENT_UPDATE"
    WAIT_ISSUER_RECOVERY = "WAIT_ISSUER_RECOVERY"
    ESCALATE_TO_MERCHANT = "ESCALATE_TO_MERCHANT"
    STOP_MARK_CHURN = "STOP_MARK_CHURN"
    NO_ACTION = "NO_ACTION"


class GateResult(str, Enum):
    ALLOWED = "ALLOWED"
    BLOCKED = "BLOCKED"


class LedgerEventType(str, Enum):
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    FAILURE_INGESTED = "FAILURE_INGESTED"
    CLASSIFIED = "CLASSIFIED"
    PREDICTED = "PREDICTED"
    DECISION = "DECISION"
    GATE_BLOCKED = "GATE_BLOCKED"
    PRESENTMENT_SENT = "PRESENTMENT_SENT"
    PRESENTMENT_RESULT = "PRESENTMENT_RESULT"
    MESSAGE_SENT = "MESSAGE_SENT"
    MESSAGE_SUPPRESSED = "MESSAGE_SUPPRESSED"
    LINK_CREATED = "LINK_CREATED"
    LINK_PAID = "LINK_PAID"
    REAUTH_REQUESTED = "REAUTH_REQUESTED"
    RECOVERED = "RECOVERED"
    ABANDONED = "ABANDONED"
    CHURN_FLAGGED = "CHURN_FLAGGED"


class Channel(str, Enum):
    WHATSAPP = "WHATSAPP"
    SMS = "SMS"
    EMAIL = "EMAIL"
    NONE = "NONE"


class RunMode(str, Enum):
    BASELINE = "BASELINE"
    AGENT = "AGENT"
    LIVE = "LIVE"
    ORACLE = "ORACLE"


class MandateRail(str, Enum):
    UPI_AUTOPAY = "UPI_AUTOPAY"
    ENACH = "ENACH"
    CARD_RECURRING = "CARD_RECURRING"


class MandateStatus(str, Enum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
    PAUSED = "PAUSED"
    AWAITING_REAUTH = "AWAITING_REAUTH"


class MandateFrequency(str, Enum):
    MONTHLY = "MONTHLY"
    WEEKLY = "WEEKLY"
    QUARTERLY = "QUARTERLY"


class CycleState(str, Enum):
    SCHEDULED = "SCHEDULED"
    IN_RECOVERY = "IN_RECOVERY"
    RECOVERED = "RECOVERED"
    ABANDONED = "ABANDONED"


class RecoveredVia(str, Enum):
    PRESENTMENT = "PRESENTMENT"
    PAYMENT_LINK = "PAYMENT_LINK"


class PredictionBasis(str, Enum):
    CUSTOMER_HISTORY = "CUSTOMER_HISTORY"
    POPULATION_PRIOR = "POPULATION_PRIOR"
    BLENDED = "BLENDED"
    ISSUER_RECOVERY = "ISSUER_RECOVERY"


class PendingActionState(str, Enum):
    PENDING = "PENDING"
    EXECUTED = "EXECUTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class CustomerSegment(str, Enum):
    """Generator ground truth. core/ must never select this column."""

    SALARIED_MONTH_START = "SALARIED_MONTH_START"
    SALARIED_MONTH_END = "SALARIED_MONTH_END"
    GIG_IRREGULAR = "GIG_IRREGULAR"
    SELF_EMPLOYED_LUMPY = "SELF_EMPLOYED_LUMPY"
