"""initial schema

Revision ID: 71bc304d90f7
Revises: 
Create Date: 2026-08-22 23:28:23.757331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71bc304d90f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_log_customer_id'), 'contact_log', ['customer_id'], unique=False)
    op.create_index('ix_contact_log_customer_run_sent', 'contact_log', ['customer_id', 'run_id', 'sent_at'], unique=False)
    op.create_table('corpus_meta',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('n_customers', sa.Integer(), nullable=False),
    sa.Column('n_mandates', sa.Integer(), nullable=False),
    sa.Column('n_cycles', sa.Integer(), nullable=False),
    sa.Column('cause_mix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adversarial_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone_e164', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('issuer_code', sa.Text(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('segment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_calendar',
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance_paise', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', 'date')
    )
    op.create_table('issuer_health',
    sa.Column('issuer_code', sa.Text(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('observed_success_rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_outage', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('issuer_code', 'as_of_date')
    )
    op.create_table('runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('corpus_id', sa.Text(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('policy_config_hash', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandates',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('rail', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('max_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('debit_day', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_subscription_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandates_customer_id'), 'mandates', ['customer_id'], unique=False)
    op.create_table('cycles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('mandate_id', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('presentations_used', sa.Integer(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered_via', sa.Text(), nullable=True),
    sa.Column('recovered_amount_paise', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycles_mandate_id'), 'cycles', ['mandate_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('cycle_id', sa.Text(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('presented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('gateway_code', sa.Text(), nullable=True),
    sa.Column('gateway_desc', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_cycle_id'), 'attempts', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_attempts_run_id'), 'attempts', ['run_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('cycle_id', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('template_key', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_rendered', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppressed_reason', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_customer_id'), 'messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_messages_cycle_id'), 'messages', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_messages_run_id'), 'messages', ['run_id'], unique=False)
    op.create_table('payment_links',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('cycle_id', sa.Text(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('razorpay_link_id', sa.Text(), nullable=True),
    sa.Column('short_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_links_cycle_id'), 'payment_links', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_payment_links_run_id'), 'payment_links', ['run_id'], unique=False)
    op.create_table('failure_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('attempt_id', sa.Text(), nullable=False),
    sa.Column('mandate_id', sa.Text(), nullable=False),
    sa.Column('cycle_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('raw_code', sa.Text(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index(op.f('ix_failure_events_customer_id'), 'failure_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_failure_events_cycle_id'), 'failure_events', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_failure_events_mandate_id'), 'failure_events', ['mandate_id'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('failure_event_id', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('subtype', sa.Text(), nullable=False),
    sa.Column('disposition', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('matched_rule', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_failure_event_id'), 'classifications', ['failure_event_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('failure_event_id', sa.Text(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('gate_result', sa.Text(), nullable=False),
    sa.Column('blocked_by', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('inputs_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_failure_event_id'), 'decisions', ['failure_event_id'], unique=False)
    op.create_index(op.f('ix_decisions_run_id'), 'decisions', ['run_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('failure_event_id', sa.Text(), nullable=False),
    sa.Column('curve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('best_day_offset', sa.Integer(), nullable=False),
    sa.Column('best_p', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('feature_contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_failure_event_id'), 'predictions', ['failure_event_id'], unique=False)
    op.create_table('ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ulid', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wall_clock_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('mandate_id', sa.Text(), nullable=True),
    sa.Column('cycle_id', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('decision_id', sa.Text(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corrects_ledger_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ulid')
    )
    op.create_index(op.f('ix_ledger_run_id'), 'ledger', ['run_id'], unique=False)
    op.create_table('pending_actions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('decision_id', sa.Text(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_decision_id'), 'pending_actions', ['decision_id'], unique=False)
    # ### end Alembic commands ###

    # docs/03-DATA-MODEL.md: the ledger is append-only. No UPDATE, no DELETE.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION ledger_is_append_only() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'ledger is append-only (attempted %)', TG_OP;
        END; $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER ledger_no_update BEFORE UPDATE OR DELETE ON ledger
        FOR EACH ROW EXECUTE FUNCTION ledger_is_append_only();
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS ledger_no_update ON ledger")
    op.execute("DROP FUNCTION IF EXISTS ledger_is_append_only()")
    op.drop_index(op.f('ix_pending_actions_decision_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_ledger_run_id'), table_name='ledger')
    op.drop_table('ledger')
    op.drop_index(op.f('ix_predictions_failure_event_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_decisions_run_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_failure_event_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_classifications_failure_event_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_failure_events_mandate_id'), table_name='failure_events')
    op.drop_index(op.f('ix_failure_events_cycle_id'), table_name='failure_events')
    op.drop_index(op.f('ix_failure_events_customer_id'), table_name='failure_events')
    op.drop_table('failure_events')
    op.drop_index(op.f('ix_payment_links_run_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_cycle_id'), table_name='payment_links')
    op.drop_table('payment_links')
    op.drop_index(op.f('ix_messages_run_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_cycle_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_customer_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_attempts_run_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_cycle_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_cycles_mandate_id'), table_name='cycles')
    op.drop_table('cycles')
    op.drop_index(op.f('ix_mandates_customer_id'), table_name='mandates')
    op.drop_table('mandates')
    op.drop_table('runs')
    op.drop_table('issuer_health')
    op.drop_table('funding_calendar')
    op.drop_table('customers')
    op.drop_table('corpus_meta')
    op.drop_index('ix_contact_log_customer_run_sent', table_name='contact_log')
    op.drop_index(op.f('ix_contact_log_customer_id'), table_name='contact_log')
    op.drop_table('contact_log')
    # ### end Alembic commands ###
